name       : dbeaver
version    : 22.2.3
release    : 52
source     :
    - https://github.com/dbeaver/dbeaver/archive/refs/tags/22.2.3.tar.gz : 07b31dfa46b9c1d0d67ec06040cedeac1b0431123acd426a62808c6df0c4b2ea
license    : Apache-2.0
component  : database
homepage   : https://dbeaver.io/
summary    : Free universal database manager and SQL client
description: |
    Free multi-platform database tool for developers, SQL programmers, database administrators and analysts.
networking : yes
builddeps  :
    - apache-maven
    - openjdk-17
rundeps    :
    - openjdk-17
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-17
    export PATH=$JAVA_HOME/bin:$PATH
setup      : |
    %patch -Np1 < $pkgfiles/0001-Disable-auto-update-check-by-default.patch
    %patch -p1 < $pkgfiles/0001-Change-default-theme-to-dark.patch

    sed -i "s|<target>11</target>|<target>17</target>|" pom.xml
    sed -i "s|<compilerVersion>1.8</compilerVersion>|<compilerVersion>17</compilerVersion>|" pom.xml
build      : |
    export MAVEN_OPTS="-Xmx1024m"
    mvn -Dmaven.repo.local=$workdir/.m2 package
install    : |
    export _target_dir=product/community/target/products/org.jkiss.dbeaver.core.product/linux/gtk/x86_64/dbeaver

    install -dm00755 $installdir/usr/{bin,share}/
    cp -a $_target_dir $installdir/usr/share
    ln -s /usr/share/dbeaver/dbeaver $installdir/usr/bin/dbeaver

    for _size in 16 32 48 64 128 256 512
    do
      install -Dm00644 product/community/icons-sources/icon_${_size}x${_size}.png \
        $installdir/usr/share/icons/hicolor/${_size}x${_size}/apps/dbeaver.png
    done

    # Make dbeaver compatible with icon themes
    install -dm00755 $installdir/usr/share/pixmaps/
    rm -vf $installdir/usr/share/dbeaver/icon.xpm
    install -Dm00644 $_target_dir/dbeaver.png $installdir/usr/share/pixmaps/dbeaver.png
    install -Dm00644 $_target_dir/icon.xpm $installdir/usr/share/pixmaps/dbeaver.xpm

    install -Dm00644 $pkgfiles/io.dbeaver.DBeaver.desktop -t $installdir/usr/share/applications/

    # Set the correct OpenJDK
    sed -i '/-vmargs/i -vm\n/usr/lib64/openjdk-17/bin/java' $installdir/usr/share/dbeaver/dbeaver.ini
