name       : dbeaver
version    : 4.3.5
release    : 8
source     :
    - https://github.com/dbeaver/dbeaver/archive/4.3.5.tar.gz : d9c7c9fb55a37423d906d58cbcd6bca8c4ee04edd5ae2a27e24c0543f673c336
license    : Apache-2.0
component  : database
summary    : Free universal database manager and SQL client
description: |
    Free multi-platform database tool for developers, SQL programmers, database
    administrators and analysts
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - openjdk-8
build      : |
    mkdir m2
    export MAVEN_OPTS="-Dmaven.repo.local=./m2"
    mvn package
install    : |
    install -D -m 00644 $pkgfiles/dbeaver.desktop $installdir/usr/share/applications/dbeaver.desktop
    install -d -m 00755 $installdir/usr/share/dbeaver
    cp -a product/standalone/target/products/org.jkiss.dbeaver.core.product/linux/gtk/x86_64/dbeaver/* $installdir/usr/share/dbeaver
    install -d -m 00755 $installdir/usr/bin
    ln -s /usr/share/dbeaver/dbeaver $installdir/usr/bin/dbeaver
