name       : dbeaver
version    : 7.1.0
release    : 36
source     :
    - https://github.com/dbeaver/dbeaver/archive/7.1.0.tar.gz : db91db507e48196399a755ffeeea7fc61bafc9737693041ad5e2f9fe316004a3
license    : Apache-2.0
component  : database
summary    : Free universal database manager and SQL client
description: |
    Free multi-platform database tool for developers, SQL programmers, database administrators and analysts.
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - openjdk-11
setup      : |
    %patch -Np1 < $pkgfiles/0001-Disable-auto-update-check-by-default.patch
build      : |
    mkdir m2
    mvn -Dmaven.repo.local=./m2 package
install    : |
    install -Dm00644 $pkgfiles/dbeaver.desktop -t $installdir/usr/share/applications
    install -dm00755 $installdir/usr/share
    cp -a product/standalone/target/products/org.jkiss.dbeaver.core.product/linux/gtk/x86_64/dbeaver $installdir/usr/share
    install -dm00755 $installdir/usr/bin
    ln -s /usr/share/dbeaver/dbeaver $installdir/usr/bin/dbeaver

    # Set the correct OpenJDK
    sed -i '/-vmargs/i -vm\n/usr/lib64/openjdk-11/bin/java' $installdir/usr/share/dbeaver/dbeaver.ini
