name       : dbeaver
version    : 3.8.2
release    : 1
source     :
    - https://github.com/serge-rider/dbeaver/archive/3.8.2.tar.gz : 0a4ec2f34accbc5cee9ed8f8168996ad9f5db5a52af1083f2708c65f423ff361
license    : GPL-2.0
component  : programming.tools
summary    : Free multi-platform database tool for developers, SQL programmers, database administrators and analysts
description: |
    Free multi-platform database tool for developers, SQL programmers, database administrators and analysts
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - openjdk-8
build      : |
    mkdir m2
    export MAVEN_OPTS="-Dmaven.repo.local=./m2"
    mvn package
install    : |
    install -D -m 00644 $pkgfiles/dbeaver.desktop $installdir/usr/share/applications/dbeaver.desktop
    install -d $installdir/usr/share/dbeaver
    cp -R product/standalone/target/products/org.jkiss.dbeaver.core.product/linux/gtk/x86_64/dbeaver/* $installdir/usr/share/dbeaver
    install -d $installdir/usr/bin
    ln -s /usr/share/dbeaver/dbeaver $installdir/usr/bin/dbeaver
