name       : dbeaver
version    : 22.0.1
release    : 47
source     :
    - https://github.com/dbeaver/dbeaver/archive/refs/tags/22.0.1.tar.gz : 2258f77b6e68fc0784dd7d92fc1297695b57e6ca22e3d454f21f328bf61e2bf0
license    : Apache-2.0
component  : database
homepage   : https://dbeaver.io/
summary    : Free universal database manager and SQL client
description: |
    Free multi-platform database tool for developers, SQL programmers, database administrators and analysts.
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - openjdk-11
setup      : |
    %patch -Np1 < $pkgfiles/0001-Disable-auto-update-check-by-default.patch
    %patch -p1 < $pkgfiles/0001-Change-default-theme-to-dark.patch
build      : |
    mvn -Dmaven.repo.local=$workdir/.m2 package
install    : |
    export _target_dir=product/community/target/products/org.jkiss.dbeaver.core.product/linux/gtk/x86_64/dbeaver

    install -dm00755 $installdir/usr/{bin,share}/
    cp -a $_target_dir $installdir/usr/share
    ln -s /usr/share/dbeaver/dbeaver $installdir/usr/bin/dbeaver

    for _size in 16 32 48 64 128 256 512
    do
      install -Dm00644 product/community/icons-sources/icon_${_size}x${_size}.png \
        $installdir/usr/share/icons/hicolor/${_size}x${_size}/apps/dbeaver.png
    done

    # Make dbeaver compatible with icon themes
    install -dm00755 $installdir/usr/share/pixmaps/
    rm -vf $installdir/usr/share/dbeaver/icon.xpm
    install -Dm00644 $_target_dir/dbeaver.png $installdir/usr/share/pixmaps/dbeaver.png
    install -Dm00644 $_target_dir/icon.xpm $installdir/usr/share/pixmaps/dbeaver.xpm

    install -Dm00644 $pkgfiles/io.dbeaver.DBeaver.desktop -t $installdir/usr/share/applications/

    # Set the correct OpenJDK
    sed -i '/-vmargs/i -vm\n/usr/lib64/openjdk-11/bin/java' $installdir/usr/share/dbeaver/dbeaver.ini
