name       : dbeaver
version    : 21.2.0
release    : 43
source     :
    - https://github.com/dbeaver/dbeaver/archive/refs/tags/21.2.0.tar.gz : da1aefdb5b98bec0fad11524cc7860e257037770daa5f5b263b82609db2668bd
license    : Apache-2.0
component  : database
homepage   : https://dbeaver.io/
summary    : Free universal database manager and SQL client
description: |
    Free multi-platform database tool for developers, SQL programmers, database administrators and analysts.
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - openjdk-11
setup      : |
    %patch -Np1 < $pkgfiles/0001-Disable-auto-update-check-by-default.patch
    %patch -p1 < $pkgfiles/0001-Change-default-theme-to-dark.patch
build      : |
    mvn -Dmaven.repo.local=$workdir/.m2 package
install    : |
    install -dm00755 $installdir/usr/{bin,share}/
    cp -a product/community/target/products/org.jkiss.dbeaver.core.product/linux/gtk/x86_64/dbeaver $installdir/usr/share
    ln -s /usr/share/dbeaver/dbeaver $installdir/usr/bin/dbeaver

    install -Dm00644 $pkgfiles/dbeaver.desktop -t $installdir/usr/share/applications/

    # Set the correct OpenJDK
    sed -i '/-vmargs/i -vm\n/usr/lib64/openjdk-11/bin/java' $installdir/usr/share/dbeaver/dbeaver.ini
